name: Update README with latest blog posts

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@psantana5_"
          max_post_count: 5
          comment_tag_name: "MEDIUM-BLOG-POST-LIST"
          template: "\n- [$title]($url)"
          commit_message: "actions-bot: update blog posts in readme.md"
          gh_token: ${{ secrets.GIT_TOKEN }}
          readme_path: "README.md"
