name: Update README with latest blog posts

on:
  schedule:
    # Runs every 6 hours instead of every day to avoid rate limiting
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@psantana5_"
          max_post_count: 5
          comment_tag_name: "MEDIUM-BLOG-POST-LIST"
          template: "- [$title]($url)"
          commit_message: "Update README with the latest Medium blog posts"
          gh_token: ${{ secrets.GIT_TOKEN }}
          readme_path: "README.md"
          disable_sort: false
          retry_count: 3
          retry_wait_time: 60
